categories:
  file_io:
    - CreateFileA
    - CreateFileW
    - ReadFile
    - WriteFile
    - DeleteFileA
    - DeleteFileW
    - CopyFileA
    - CopyFileW
    - MoveFileA
    - MoveFileW
    - SetFilePointer
    - GetFileAttributesA
    - GetFileAttributesW
    - GetFileSize
    - FlushFileBuffers
    - FindFirstFileA
    - FindNextFileA
    - FindClose
    - SetFileAttributesA
    - GetTempPathA
  registry:
    - RegOpenKeyExA
    - RegOpenKeyExW
    - RegCreateKeyExA
    - RegSetValueExA
    - RegQueryValueExA
    - RegDeleteKeyA
    - RegDeleteValueA
    - RegEnumValueA
    - RegEnumKeyExA
    - RegCloseKey
  networking:
    - socket
    - connect
    - send
    - recv
    - bind
    - listen
    - accept
    - closesocket
    - WSAStartup
    - InternetOpenA
    - InternetConnectA
    - HttpOpenRequestA
    - HttpSendRequestA
    - InternetReadFile
    - InternetCloseHandle
    - UrlDownloadToFileA
  process_injection:
    - CreateProcessA
    - CreateProcessW
    - OpenProcess
    - CreateRemoteThread
    - VirtualAllocEx
    - WriteProcessMemory
    - ReadProcessMemory
    - QueueUserAPC
    - NtUnmapViewOfSection
    - SetThreadContext
    - ResumeThread
    - AdjustTokenPrivileges
    - DuplicateTokenEx
  memory_management:
    - VirtualAlloc
    - VirtualAllocEx
    - VirtualFree
    - VirtualProtect
    - VirtualProtectEx
    - HeapAlloc
    - HeapFree
    - GlobalAlloc
    - GlobalFree
    - LocalAlloc
    - LocalFree
    - MapViewOfFile
    - UnmapViewOfFile
  crypto:
    - CryptAcquireContextA
    - CryptCreateHash
    - CryptHashData
    - CryptDeriveKey
    - CryptEncrypt
    - CryptDecrypt
    - CryptReleaseContext
    - BCryptEncrypt
    - BCryptDecrypt
    - BCryptCreateHash
  system_info:
    - GetSystemTime
    - GetTickCount
    - GetTickCount64
    - QueryPerformanceCounter
    - GetModuleFileNameA
    - GetVersionExA
    - GetComputerNameA
    - GetUserNameA
    - GetAdaptersInfo
    - NetShareEnum
  dynamic_loading:
    - LoadLibraryA
    - LoadLibraryW
    - LoadLibraryExA
    - LoadLibraryExW
    - GetProcAddress
    - GetModuleHandleA
    - GetModuleHandleW
    - GetModuleHandleExA
    - LdrLoadDll
    - LdrGetProcedureAddress
  anti_debug:
    - IsDebuggerPresent
    - CheckRemoteDebuggerPresent
    - OutputDebugStringA
    - NtSetInformationThread
    - NtQueryInformationProcess
    - NtQueryInformationThread
    - NtQuerySystemInformation
    - NtContinue
    - ZwQuerySystemInformation
  entropy_indicators:
    - RtlRandomEx
    - RtlEncryptMemory
    - SystemFunction032
    - SystemFunction040
    - BCryptGenRandom

